"use strict";

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert("states", [
      {
        id: 1,
        name: "Acre",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2,
        name: "Alagoas",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 3,
        name: "Amazonas",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 4,
        name: "Amapá",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 5,
        name: "Bahia",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 6,
        name: "Ceará",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 7,
        name: "Distrito Federal",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 8,
        name: "Espírito Santo",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 9,
        name: "Goiás",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 10,
        name: "Maranhão",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 11,
        name: "Minas Gerais",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 12,
        name: "Mato Grosso do Sul",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 13,
        name: "Mato Grosso",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 14,
        name: "Pará",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 15,
        name: "Paraíba",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 16,
        name: "Pernambuco",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 17,
        name: "Piauí",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 18,
        name: "Paraná",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 19,
        name: "Rio de Janeiro",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 20,
        name: "Rio Grande do Norte",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 21,
        name: "Rondônia",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 22,
        name: "Roraima",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 23,
        name: "Rio Grande do Sul",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 24,
        name: "Santa Catarina",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 25,
        name: "Sergipe",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 26,
        name: "São Paulo",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 27,
        name: "Tocantins",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 28,
        name: "Alaska",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 29,
        name: "Alabama",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 30,
        name: "Arkansas",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 31,
        name: "Arizona",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 32,
        name: "California",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 33,
        name: "Colorado",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 34,
        name: "Connecticut",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 35,
        name: "District of Columbia",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 36,
        name: "Delaware",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 37,
        name: "Florida",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 38,
        name: "Georgia",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 39,
        name: "Hawaii",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 40,
        name: "Iowa",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 41,
        name: "Idaho",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 42,
        name: "Illinois",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 43,
        name: "Indiana",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 44,
        name: "Kansas",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 45,
        name: "Kentucky",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 46,
        name: "Louisiana",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 47,
        name: "Massachusetts",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 48,
        name: "Maryland",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 49,
        name: "Maine",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 50,
        name: "Michigan",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 51,
        name: "Minnesota",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 52,
        name: "Missouri",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 53,
        name: "Mississippi",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 54,
        name: "Montana",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 55,
        name: "North Carolina",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 56,
        name: "North Dakota",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 57,
        name: "Nebraska",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 58,
        name: "New Hampshire",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 59,
        name: "New Jersey",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 60,
        name: "New Mexico",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 61,
        name: "Nevada",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 62,
        name: "New York",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 63,
        name: "Ohio",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 64,
        name: "Oklahoma",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 65,
        name: "Oregon",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 66,
        name: "Pennsylvania",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 67,
        name: "Rhode Island",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 68,
        name: "South Carolina",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 69,
        name: "South Dakota",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 70,
        name: "Tennessee",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 71,
        name: "Texas",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 72,
        name: "Utah",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 73,
        name: "Virginia",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 74,
        name: "Vermont",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 75,
        name: "Washington",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 76,
        name: "Wisconsin",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 77,
        name: "West Virginia",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 78,
        name: "Wyoming",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },
  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete("states", null, {});
  },
};
